version: 2

workflows:
  version: 2
  test:
    jobs:
      - build-python-3.8
      - build-python-3.9
      - test-python-3.8

jobs:
  build-python-3.8: &template
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Builds source distribution
          working_directory: ~/project/
          # Ensure we can build a source distribution that can correctly install.
          # "python setup.py sdist" creates dist/latin_scansion-x.y.z.tar.gz
          command: |
              pip install --progress-bar off --upgrade pip setuptools
              python setup.py sdist
              pip install dist/`ls dist/ | grep .tar.gz`
      - run:
          name: Installs requirements
          working_directory: ~/project/
          command: pip install --progress-bar off --requirement requirements.txt 
      - run:
          name: Runs flake8 check
          working_directory: ~/project
          command: flake8 --exclude latin_scansion/lib/scansion_pb2.py latin_scansion setup.py tests
      - run:
          name: Runs black check
          working_directory: ~/project
          command: black --line-length 79 --check --exclude latin_scansion/lib/scansion_pb2.py latin_scansion setup.py tests
  build-python-3.9:
    <<: *template
    docker:
      - image: python:3.9
  test-python-3.8:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Builds from source and runs tests
          working_directory: ~/project
          command: |
              conda env create --quiet --file environment.yml
              source ~/.bashrc
              conda activate scansion
              make -j -C grammars
              make -C latin_scansion/lib
              pip install --editable .
      - run:
          name: Runs pytest
          working_directory: ~/project
          command: |
              source ~/.bashrc
              conda activate scansion
              pytest -v tests
      - run:
          name: Runs latin_scan --help
          working_directory: ~/project
          command: |
              source ~/.bashrc
              conda activate scansion
              latin_scan --help
      - run:
          name: Runs latin_validate --help
          working_directory: ~/project
          command: |
              source ~/.bashrc
              conda activate scansion
              latin_validate --help
